### ISSUE TITLE
any update on the integration for letsencrypt

### ISSUE THREAD

**Issue by vesper8** [Larastudio/stedding#4]
I understand this part needs to be done manually? I think other playbooks have figured out how to automate this.. I was wondering if you've managed to do the same but perhaps just haven't updated this repo with all your latest improvements?

Would love to see what steps exactly need to be taken to get letsencrypt working as seamlessly as possible.. ideally automated with automatic renewals as well

**Comment by jasperf** [comment]
In this package it does require a manual setup. I have however been working on a [fork](https://github.com/Larastudio/anstead) of the excellent [Anstead Ansible playbook for Laravel
](https://github.com/ptibbetts/anstead) by @ptibbetts . It is based of [Trellis](https://roots.io/trellis/) and it does 

- automate Let's Encrypt installation or the installation of one of your own, 
- it does setup of multiple servers and 
- takes care of deployment as well as provisioning

 I am more focussing on that fork now. Just updated PHP to 7.2 for example. Only thing I am missing now is a way to add multiple databases. That and possibly working locally with Docker instead of Vagrant.
